site_name: Autonav
site_url: https://ricardo-s-santos.github.io/AutoNAV/
repo_url: https://github.com/ricardo-s-santos/AutoNAV
nav:
  - Home: index.md
  - Functions: functions.md
  - Examples: generated/gallery
  - Development: dev.md

watch:
  - ../autonav

theme:
    name: material
    palette:
     # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    logo: https://github.com/ricardo-s-santos/AutoNAV/blob/main/docs/docs/figures/icon120x120.png?raw=true
    favicon: https://github.com/ricardo-s-santos/AutoNAV/blob/main/docs/docs/figures/favicon.ico?raw=true
    features:
      - navigation.instant
      - navigation.expand
      - navigation.indexes
      - navigation.tabs
      - navigation.tabs.sticky
      - toc.integrate

plugins:
  - search
  - gallery:
        examples_dirs: docs/examples
        gallery_dirs: docs/generated/gallery
        within_subsection_order: FileNameSortKey
        run_stale_examples: true
        reset_modules: [ ]
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
          options:
            docstring_style: google
            show_root_toc_entry: false
            show_submodules: no
            heading_level: 2
            line_length: 80
            show_signature_annotations: true
            separate_signature: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      guess_lang: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
