name: Coverage

on:
  pull_request:
    branches: [main]
    paths: ["autonav/**", "tests/**", ".github/workflows/cov.yml"]
  push:
    branches: [main]
    paths: ["autonav/**", "tests/**", ".github/workflows/cov.yml"]
    tags: "*"

jobs:
  determine-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup latest Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install pip --upgrade
          pip install .[devel]
      - name: Test with pytest and create coverage report
        run: pytest --cov=autonav --cov-report=xml --test-level=ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage.xml
